version: '3.8'

services:
  frontend:
    build:
      context: ./path-to-your-react-app
    ports:
      - "80:80"

  backend:
    build:
      context: ./path-to-your-fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://root:1234@db:3306/clicks_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: clicks_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
